// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdgwREb0F59uPpbEvIP8aO_X7VEWUbZIw',
    appId: '1:556888706503:android:8f1a1744702e43fc095de2',
    messagingSenderId: '556888706503',
    projectId: 'arenax-d3bc1',
    storageBucket: 'arenax-d3bc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyq7LZikmgn6tmBxriuhFByq1T1i41y2Y',
    appId: '1:556888706503:ios:50a5f04e22210df0095de2',
    messagingSenderId: '556888706503',
    projectId: 'arenax-d3bc1',
    storageBucket: 'arenax-d3bc1.firebasestorage.app',
    androidClientId: '556888706503-55j0ihk13ssbfmindr5c6q0sce00sl5u.apps.googleusercontent.com',
    iosClientId: '556888706503-lig82cvsjkf0mvcqnssf7lv112nupsus.apps.googleusercontent.com',
    iosBundleId: 'com.example.arenax',
  );
}
